query getPayment($id: String, $type: String, $lang: String) @context(scope: "private") {
  payment(id: $id) {
    code
    name
    paymentAlias
    rule {
      isDefault
    }
    creditCardActive
    bankInvoiceActive
    redirectActive
    appInstalled
    minimumInstallmentValue
    minimumValue
    minimumValueBankInvoice
    numberOfInstallments
    numberOfInstallmentsInterestFree
    affiliation {
      configuration
    }
  }
}
